name: CI Frontend

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/angular

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencias
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/angular/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar Linter y guardar resultados
        run: |
          mkdir -p ../../../test-reports
          echo "## 🧹 Resultados de Linter - $(date)" > ../../../test-reports/lint-results.md
          echo '```' >> ../../../test-reports/lint-results.md
          npm run lint >> ../../../test-reports/lint-results.md || echo "Linting completed with issues"
          echo '```' >> ../../../test-reports/lint-results.md

      - name: Ejecutar pruebas unitarias y guardar resultados
        run: |
          mkdir -p ../../../test-reports
          echo "## 🧪 Resultados de Pruebas - $(date)" > ../../../test-reports/test-results.md
          echo '```' >> ../../../test-reports/test-results.md
          npm run test -- --watch=false --browsers=ChromeHeadless --reporters=progress >> ../../../test-reports/test-results.md
          echo '```' >> ../../../test-reports/test-results.md

      - name: Subir reportes como artefactos
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: ../../../test-reports/

      - name: Commit y push de resultados
        run: |
          git config --global user.name "Lotiel-Dev"
          git config --global user.email "karlos817gerceis@gmail.com"
          git add test-reports/lint-results.md test-reports/test-results.md
          git commit -m "📋 Actualizar resultados de lint y pruebas [skip ci]" || echo "Sin cambios"
          git push